[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning entirely (VITE_ variables are meant to be public)
  SECRETS_SCAN_ENABLED = "false"
  # Enable aggressive compression and optimization
  VITE_BUILD_OPTIMIZE = "true"

# Build processing and compression settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: *.githubusercontent.com; font-src 'self' data:; frame-src 'self' *.google.com *.googleusercontent.com drive.google.com docs.google.com; connect-src 'self' *.google-analytics.com *.analytics.google.com *.googletagmanager.com api.github.com;"

# Text Compression and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Enable text compression (Netlify auto-enables gzip, this ensures optimal settings)
    Vary = "Accept-Encoding"

# Cache and compress JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

# Cache and compress CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

# Compress HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/html; charset=utf-8"

# Compress JSON files
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/json; charset=utf-8"

# Compress XML files (sitemap)
[[headers]]
  for = "*.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml; charset=utf-8"

# Compress text files (robots.txt)
[[headers]]
  for = "*.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/plain; charset=utf-8"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize font caching and compression
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"

# Optimize image caching
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml; charset=utf-8"

# Handle form submissions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200 